### ISSUE TITLE
psycopg2.ProgrammingError

### ISSUE THREAD

**Issue by sindile** [cartologic/fgdb2postgis#5]
I am trying to import based on the attached xml file which I had imported into a filegeodatabase
[CollectionMapper.zip](https://github.com/cartologic/fgdb2postgis/files/1828958/CollectionMapper.zip)

I get the following error:

 Connect to database ...

Updating database views ...

Creating schemas ...

Loading database tables ...
0...10...20...30...40...50...60...70...80...90...100 - done.

Applying sql scripts ...
Traceback (most recent call last):
  File "c:\python27\arcgis10.3\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\arcgis10.3\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\ArcGIS10.3\Scripts\fgdb2postgis.exe\__main__.py", line 9, in <module>
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis\__main__.py", line 83, in main
    postgis.apply_sql(filegdb)
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis\postgis.py", line 99, in apply_sql
    self.execute_sql(sql_file)
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis\postgis.py", line 108, in execute_sql
    cursor.execute(code)
psycopg2.ProgrammingError: column "OBJECTID" of relation "PlantCenter" does not exist
LINE 2: INSERT INTO "PlantCenter" ("OBJECTID")

**Comment by gmioannou** [comment]
Please try the latest version (0.3.6) from Pypi
Compatible with python 3.6.9 and ArcGIS Pro 2.5.1
